### ISSUE TITLE
ISSUE - /inv remove <world> <inv>

### ISSUE THREAD

**Issue by turtledude01** [trentech/ProjectInventories#11]
This is relatively MAJOR.  I loaded a new world in using Pjw, and was configuring the invs for it... thats when it happened... I was removing the Default inv from the world, and suddenly BAM the server said something about "admin deleted this inv, getting default" and it reset EVERYONE to an empty (default) inv.  My setup was this: all the main worlds have the DEFAULT inv as their default, but this new world was not supposed to have it at all.  Removing the inv from it caused a pretty insane break.... If I can provide any extra info please let me know and i will

**Comment by trentech** [comment]
What version are you using?

**Comment by turtledude01** [comment]
Pji 0.10.0 
Spongevanilla 1.11.2 beta 207 (API 6)

**Comment by trentech** [comment]
So looking into this I couldn't find any reason inventories would be deleted. the remove command doesn't delete anything it just un-assigns inventories from worlds. Are you sure you didn't accidentally run the /inv delete command by accident?

**Comment by turtledude01** [comment]
I dont think i used the wrong command, but i just tried it again, this time with noone online and it worked as expected... BUT if there is ANY user USING the inv that is being removed from ANY world, it causes their inv to get wiped... Im going to request at least a warning saying "if anyone is currently using this inventory in any world they will lose ALL items" Thanks

**Comment by trentech** [comment]
update to latest release

**Comment by turtledude01** [comment]
I just updated to the new release and this seems to still happen... in a way...
So heres the situation:
Be in world A
remove the DEFAULT inv from world B while having the DEFAULT inv in world A
message saying the default inv was deleted so changing to the worlds default
-heres where it gets strange for me...
/inv get DEFAULT while in world A brings back the inv that was previously loaded before running the /inv remove command.  

I can load a clean server and run this while recording later this week if youd like.

**Comment by trentech** [comment]
Ah, I believe I found the issue. It's nothing destructive as you've pointed out. It's changing all players who currently have DEFAULT equipped regardless of what world they are in. Nothing is physically being deleted, it's just changing the inventory the player is currently using. Player can simply change it back as a workaround. I'll have this resolved shortly

**Comment by trentech** [comment]
Test this build https://trentech.org/jenkins/job/Project%20Inventories/
