### ISSUE TITLE
Inventory wiped on world change

### ISSUE THREAD

**Issue by turtledude01** [trentech/ProjectInventories#14]
I have 2 worlds (world1 and world2) World1 is survival, world2 is creative.  the Default inv in world1 is DEFAULT and the default inv in world2 is DEFAULT2.  DEFAULT inv is not in world2 at all.  When a player tp's from world1 to world2, their inv changes as expected.  When they tp back to world1 from world2 their inv is empty.  I ran a few tests and it seems this ONLY happens on their first join to the world.

**Comment by trentech** [comment]
I'll have to test this out. Might not be until tomorrow, I just did a clean install on my computer few days so I still gotta setup my development environment.

**Comment by aWitch-Doctor** [comment]
I'm having the same issue, the server has been established and there are too many players to risk losing their inventories or ask them to put everything in a chest. I'm not sure what info you need, tell me and ill get it for you. Hell for all i know i screwed something up when i added the plugin.

**Comment by trentech** [comment]
Update to latest release
