### ISSUE TITLE
Request features

### ISSUE THREAD

**Issue by aWitch-Doctor** [trentech/ProjectInventories#16]
I know there are already issues created for these but they haven't seen any action for awhile and I want to make sure there is something recent about this. I know you are busy with real life things and you have no idea how much I appreciate your hard work on this plugin. This plugin alone is a major part of the server I assist in running and we are lacking several features just because we don't have multi world inventory support.

Can you make it so your plugin will save the players inventory to the worlds corresponding inventory on first world change. Right now, after loading your plugin the first time the player changes worlds (when your plugin begins to track the player) it will clear the players inventory for both worlds instead of importing the players inventory to the database for the world they are coming from.

Can you also add support for enderchest inventories, I cant create a creative or sky block inventory if the players can just add items to an enderchest to take them back to another world/inventory.

**Comment by trentech** [comment]
I think this may be bug. It's intended to act like that. I've made quite a few changes to the 6.0.0 branch that should have this fixed I think.

EnderChests are a planned feature, but would suggest disabling them for the time being using an item ban plugin. StackBan is a plugin of mine that can provide that.

**Comment by aWitch-Doctor** [comment]
6.0.0 branch? do you mean sponge api 6? If so will there be a release for api 5?

There are no errors in console for this either.

**Comment by aWitch-Doctor** [comment]
I have played with this multiple times, I can't seem to get the inventories to stay. They get wiped everything on first world change. I may be doing something wrong, I don't know. Any suggestions or do we want to call this a bug?

**Comment by EvilCh33z** [comment]
My players' inventories (and my own) do the same thing on initial world change but no issues after that. I have had a permanent warning to clear inventories before the first trip in my MOTD since I discovered it and lost a few things myself.

**Comment by trentech** [comment]
Should be resolved in latest release. EnderChests added as well
