### ISSUE TITLE
[6.1.0-0.11.0.jar build #19] Configuration does not accept objects of type class java.util.Optional

### ISSUE THREAD

**Issue by bhi-elliot** [trentech/ProjectInventories#24]
Originally submitted to [Sponge](https://github.com/SpongePowered/SpongeForge/issues/1661#issuecomment-316493664), but they say it is an issue with PI:

The following came up in the server log. Not sure what caused it. Perhaps something to do with Project Inventories? The only thing I can think might have been happening at the time was OP giving an item to itself (as in, from NEI perhaps). Hope this helps! Thank you for everything!
[Pastebin of just the error](https://pastebin.com/7CahQ8ii)

I am currently running:
- SpongeForge version: spongeforge-1.11.2-2393-6.1.0-BETA-2468
- Forge version: forge-1.11.2-13.20.1.2414-universal
- Java version: 1.8.0_131
- Operating System: Windows 10

Plugins (37): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, FoamFixCore, ccl-entityhook, AdventureMMO, BiblioCraft, Biomes O' Plenty, BiblioWoodBoP, BiblioWoodForestry, BuildCraft Lib, BuildCraft, BC Builders, BC Energy, BC Factory, BC Robotics, BC Silicon, BC Transport, CodeChicken Lib, FoamFix, IndustrialCraft 2, Just Enough Items, Forestry, FoxCore, FoxGuard, Iron Chest, LuckPerms, Not Enough Items, Nucleus, Project Core, Project Inventories, Project Portals, Project Worlds, WorldEdit

**What is the expected result?**
No error.

**What is the current result?**
Error and I believe the item did not get created.

fml-server-latest.log and server.log: https://gist.github.com/bhi-elliot/0ca94c17c184974f791928de907ebcb1

**Comment by trentech** [comment]
What version of PJI and where was it obtained? I see all my plugins have b19 or similar in the jar names which isn't something I produce. The line numbers in the error log don't match any of my builds so I'm unsure where the error is occuring

**Comment by bhi-elliot** [comment]
Hello!
Thank you very much for the reply. I really appreciate the help!
It was the latest (at the time) version of PJI. Build #19 of project inventories-6.1.0-0.11.0
This one:
https://trentech.org/jenkins/job/Project%20Inventories/19/

Got it right from you. Since your naming convention does not include build numbers, I renamed the file so I would know which build it was when checking for updates in the future.

Does that make sense?
Thanks, again, for looking into this. I'm happy to help with anything I can as I'd love for this plugin to work on my server.

Peace.

**Comment by trentech** [comment]
gotcha. That was my bad, I was looking at my 7.x branch..This isn't the first time this error has been reported but I've been having a hell of a time figuring out what could be causing it as I've yet to replicate the issue. My assumption is its related to some mod but until I replicate the issue I won't know for sure.

**Comment by trentech** [comment]
So I just pushed some changes that I apparently have been sitting on, to the jenkins server. I don't really know if it'll help but I'm curious to see the results.

**Comment by bhi-elliot** [comment]
Below is my mod list if that helps. If I were to make a guess, I would think it is either BuildCraft or IC2, as those two seem to be still heavily under development... but who knows. Could be any of them that add custom items...
That being said, I know it happened to me once and I was not carrying anything from a mod, they were all vanilla items.

Another thing of note is that every player on my server has experienced it except for my admin character, who is OP and has all permissions and is always in Creative mode.

To get the player's inventory to stop freaking out, I use the /inventory see, remove all their items into my admin's inventory, put that stuff in chests, teleport the player around to different worlds, restart the server, put just a regular piece of dirt in their inventory, warp them around a few more times (to get the inventory to change from world to world and 'hopefully' reload properly), maybe restart the server once more and then they are fine.

Not sure if any of that is helpful.

Thanks for pushing changes. Means a lot!
I'll give it a go and will report back if it happens again and will try to make note of anything specific the player was holding or interacting with...
When it happened to me (just my non-admin character), it felt like the query to the database got stuck in a loop because I could interact with anything or open my inventory. I kept getting "Please wait while your inventory updates".

Thanks!

Sponge plugins:
AdventureMMO
UniverseGuard
LuckPerms
Nucleus
Project Core
Project Inventories
Project Portals
Project World
WorldEdit

Mods:
Aroma Backup
Aroma Core
Better FPS
BiblioCraft
Bibliowoods
Biomes O' Plenty
BuildCraft
CodeChickenLib
FoamFix
Forestry
IndustrialCraft 2
IronChest
Just Enough Items
Not Enough Items

**Comment by bhi-elliot** [comment]
Hello again,

I did some testing today. I found that I received the same error as above when equipping an enchanted and named diamond helmet. I am not sure if it is the fact that it is enchanted, or named, or just a coincident. The server had been running for over an hour and I had been doing normal vanilla things, placing/breaking blocks. I was carrying a Biomes O' Plenty flower in my inventory as well.

Hope that can help,

**Comment by bhi-elliot** [comment]
Can make it repeat. Build 23.
All vanilla items in inventory and interacting with.
Restarted server, logged in, played for a while, took a named enchanted helmet out of a wooden chest, put it on, went about doing my thing and received the error message just as I was placing a block.

**Comment by bhi-elliot** [comment]
I've been able to make it happen by just logging in and putting on vanilla leather boots with no enchantment or naming.

**Comment by trentech** [comment]
So sounds like its related to the equipment slots then..OK that helps. I'll be doing some tests later

**Comment by trentech** [comment]
Can you post a recent server log that includes any errors?

**Comment by trentech** [comment]
OK I finally figured out what's going on. I also received that null exception that you posted in a different issue and it's also related. That is because my screw up caused a null value in the player database. Seems tping around and restarting the server fixes that error after updating to working version of pji.

**Comment by bhi-elliot** [comment]
Thanks for looking into it.
There were some logs in the OP, but here are fresh ones. All that happened during this logged sequence was I logged in with a regular player in survival mode, grabbed some leather boots out of a chest, put them on, ran around a bit, put down a few redstone torches, and received the error. Then turned server off.

[latest.log](https://pastebin.com/41R28H6k)
[fml-server-latest.log](https://gist.github.com/bhi-elliot/906a7cce924085411421723aa8a13135)
[fml-junk-earlystartup.log](https://gist.github.com/bhi-elliot/d78c9fb02f6385c80e97061b39d13366)


Java version: 1.8.0_144
minecraft_server.1.11.2
forge-1.11.2-13.20.1.2425-universal
spongeforge-1.11.2-2393-6.1.0-BETA-2484

_Sponge plugins:_
AdventureMMO-v2.0.7-API6.x
LuckPerms-Sponge-3.2.58 b271
Nucleus-1.0.1-LTS-1.11.2-1.12-S6.0-plugin
project core-6.1.0-0.1.0 b19
project inventories-6.1.0-0.11.0 b23
project portals-6.1.0-0.14.0 b17
project worlds-6.1.0-0.12.0 b35
UniverseGuard
worldedit-sponge-6.1.8-SNAPSHOT-dist b3696

_Mods:_
Aroma1997Core-1.11.2-1.2.0.0
AromaBackup-1.11-2.1.0.0
BetterFps-1.4.5
BiblioCraft[v2.3.3][MC1.11.2]
BiblioWoods[BiomesOPlenty][v2.0][MC1.11.2]
BiblioWoods[Forestry][v2.0][MC1.11.2]
BiomesOPlenty-1.11.2-6.2.0.2267-universal
buildcraft-7.99.6
CodeChickenLib-1.11.2-3.0.0.287-universal
foamfix-0.7.2-anarchy
forestry_1.11.2-5.3.4.152
industrialcraft-2-2.7.81-ex111
ironchest-1.11.2-7.0.25.815
jei_1.11.2-4.5.0.294
NotEnoughItems-1.11.2-2.3.0.227-universal

_Client additions:_
OptiFine_1.11.2_HD_U_C3
WorldEdit CUI Forge Edition 2-2.1.1-mf-1.11.2-13.20.0.2228


Hope that helps!

**Comment by trentech** [comment]
Read my above post. please test that build, I believe it's resolved

**Comment by bhi-elliot** [comment]
Great work!
So far it seems to be holding as of build 25. Excellent! Thank you!

I'm not sure if this is new, or something caused by your recent changes, but it seems now that xp is not saved, so resets when a player logs out and back in... or when server restarts... or when a player goes from one world to another and back.
If this is a separate issue, I can make a separate GitHub issue if you like.

thanks again for your hard work!

**Comment by trentech** [comment]
So I just did some testing and that's is a Sponge bug from the looks of it. It's happening without PJI installed. From what I can tell it's only a visual bug. After collecting more experience the original values return.
