### ISSUE TITLE
Default Inventory Behavior

### ISSUE THREAD

**Issue by TripleSixes** [trentech/ProjectInventories#28]
I have created an inventory for each of my worlds, and added the respective inventories to said worlds as default using (/inventory add survival SURVIVAL true)

When I do /inventory info, I get output saying that SURVIVAL is the default inventory for the survival world, but when I enter the world, I still default to the DEFAULT inventory.

I am on projectinventories-5.2.0-0.10.1 and currently running 
Minecraft Version: Minecraft Optional[1.10.2]
Sponge Version: SpongeForge 1.10.2-2254-5.2.0-BETA-2234
Sponge API Version: SpongeAPI 5.2.0-SNAPSHOT-a3257a0

Thoughts?

**Comment by trentech** [comment]
Because you can have multiple inventories in one given world, when entering said world, you will see the last inventory that was open in that world. So if you change the SURVIVAL before leaving that world, it should open SURVIVAL the next time to enter. You can also change default-on-world-change to true in the config to have the inventory always set to the default for that world.

**Comment by TripleSixes** [comment]
It seems like default-on-world-change is not working properly for me. It is set to true, but new users who walk into the survival world then the hub are able to smuggle items out, as they are still being defaulted to DEFAULT instead of SURVIVAL(default).

**Comment by trentech** [comment]
Did you reload or restart the server after editing the config? If your plan is to have completely separate inventories per world I would recommend removing the default inventory entirely from your survival world. That would solve your smuggling situation.

**Comment by TripleSixes** [comment]
I will try reloading and restarting after editing the config, I tried to remove the default inventory in-game but it wouldn't let me ("DEFAULT inventory cannot be altered or deleted").

**Comment by trentech** [comment]
The remove command and delete command are different. Delete permanently deletes the inventory from the server, remove only removes it from the specified world.

**Comment by TripleSixes** [comment]
I will give it another go and report back 👍 Thank you for the quick responses thus far!

**Comment by TripleSixes** [comment]
/inventory delete DEFAULT does not work either, same error message. I have had a new player enter survival and they still default to DEFAULT rather than SURVIVAL(default)

**Comment by TripleSixes** [comment]
Hey Trentech, just wanted to say that I resolved my problem. When I was trying to delete DEFAULT, I did not specify which world to do it in. It works perfectly now!

Thanks~ (^)>/
