### ISSUE TITLE
Feature request. Add change game modes

### ISSUE THREAD

**Issue by ziceptor** [trentech/ProjectInventories#30]
Add change game modes when switching between worlds.

**Comment by trentech** [comment]
Apparently I never updated the help stuff but this feature is already in the plugin. The `/inv create `command has flags. `/inv create <name> [-p <permissionNode>] [-g <gamemode>]`
`-g` flag assigns the inventory a gamemode, so whenever someone switches to that inventory, whether it be triggered from changing worlds or simply running the` /inv get` command, the gamemode will also switch to whatever it's set to. The `-p` flag as you probably guessed assigns a required permission node to that inventory. players will need the permission to switch to that inventory with `/inv get`. This is overridden if triggered by switching worlds.

**Comment by ziceptor** [comment]
And how to edit the inventory? Just to re-create?

**Comment by trentech** [comment]
running the `/inv create` again will modify any existing inventories already created

**Comment by ziceptor** [comment]
/inv c he -g survival and /inv c he -g 0 output command format /inv create <name> [-g <gamemode>] [-p <permissionNode>] No errror in console.

**Comment by ziceptor** [comment]
no value -g mathing 0

**Comment by ziceptor** [comment]
minecraft:survival need

**Comment by ziceptor** [comment]
I did /inv c he -g minecraft:survival
I did /inv c custom -g minecraft:survival
I did /inv c wflat -g minecraft:survival

```
DEFAULT | {"name":"DEFAULT"}
-- | --
CUSTOM | {"name":"CUSTOM","gamemode":"minecraft:survival"}
ZICRAFT | {"name":"ZICRAFT","gamemode":"minecraft:survival"}
WFLAT | {"name":"WFLAT","gamemode":"minecraft:survival"}
HE | {"name":"HE","gamemode":"minecraft:survival"}
```

But if you run /gm 0. Then going to another world will remain creative.

**Comment by ziceptor** [comment]
```
options {
    # Always set inventory to world default when entering
    default-on-world-change=true
    # Enable inventory specific experience
    experience=true
    # Enable inventory specific health
    health=true
    # Enable inventory specific hunger
    hunger=true
    # Seperate ender chest inventory for each world
    per-world-enderchests=true
    # Enable inventory specific potion effects
    potion-effects=true
}

```

**Comment by trentech** [comment]
Have you assigned the inventories to the worlds?

**Comment by trentech** [comment]
```
/inv c he -g minecraft:survival
/inv c custom -g minecraft:survival
/inv c wflat -g minecraft:survival
/inv a wflat wflat true
/inv a custom custom true
/inv a he he true
```

true marks it as the default inventory for that world

**Comment by ziceptor** [comment]
yes 


```
e03fd75b-f590-4e77-9786-afe11c7f338b | {"name":"e03fd75b-f590-4e77-9786-afe11c7f338b","inventories":{"CUSTOM":true,"DEFAULT":false}}
-- | --
5a04cc5f-19ca-45a2-ae94-530913fd5109 | {"name":"5a04cc5f-19ca-45a2-ae94-530913fd5109","inventories":{"ZICRAFT":true,"DEFAULT":false}}
7f14d433-9c0e-4835-b8a5-9d567347f1ba | {"name":"7f14d433-9c0e-4835-b8a5-9d567347f1ba","inventories":{"DEFAULT":false,"WFLAT":true}}
52d1a6d5-528a-4cd9-89ca-e7eed32ae641 | {"name":"52d1a6d5-528a-4cd9-89ca-e7eed32ae641","inventories":{"HE":true,"DEFAULT":false}}
```

**Comment by trentech** [comment]
default-on-world-change=true

change this to false

**Comment by ziceptor** [comment]
The inventory changes. Not only change the game mode.

> change this to false

ok. try

**Comment by trentech** [comment]
OK check your permissions. There's a pji.override.gamemode node that overrides this feature.

**Comment by ziceptor** [comment]
The player you do not have permission pji.override.gamemode

**Comment by ziceptor** [comment]
default-on-world-change=false the problem remained

**Comment by ziceptor** [comment]
something has ceased to change even the inventory :)

**Comment by ziceptor** [comment]
I did for the player `/inv g HE` and the plugin started working correctly. Probably somewhere there is a problem.
