### ISSUE TITLE
Major Bug L(0)(0)K

### ISSUE THREAD

**Issue by SkylixMC** [trentech/ProjectInventories#42]
Not sure if this plugin is still being maintained but a few major bugs that is a deal breaker for 90% of all users:

- Inventory is kept even if keep inventory is disabled.
- Incompatible with graves mod

**Comment by trentech** [comment]
This is a permissions issue not a bug. Players with pji.keepinventory will keep inventory on death. This plugin should have no baring on how the graves mod works.
