### ISSUE TITLE
[1.10.2] Keep inventory on death

### ISSUE THREAD

**Issue by Souperhero** [trentech/ProjectInventories#5]
When I'm killed, I keep my inventory on death rather than using a grave or spilling my stuff everywhere.

**Comment by trentech** [comment]
This plugin doesn't change death drops. Is it dropping items on death but not clearing inventory?

**Comment by Souperhero** [comment]
Pulled ProjectInventory out, and the problem is persisting. Will keep looking into it.

Made sure /gamerule keepInventory was false.

Thank you for your assistance! :)
