### ISSUE TITLE
Off-hand item lost on inventory save

### ISSUE THREAD

**Issue by specialkk** [trentech/ProjectInventories#7]
I'm on 0.8.1 with Sponge API 5.0.0, and it still seems like saving the off hand item is broken even with 5f443b9. I did a bit of probing it looks like the following is true:

```
PlayerInventory inv = player.getInventory().query(PlayerInventory.class);
inv.getOffhand().peek(); // Is always an empty stack
```

I'm not sure if this is an issue with Sponge, or an issue with the PlayerInventory query, or maybe both.

**Comment by trentech** [comment]
This will be solved in next major update coming soon
