### ISSUE TITLE
[1.10.2 / Sponge 5.1.0-BETA-1961 / pji-5.1.0-0.9.1 to pji-5.1.0-0.9.1] All inv forced to default after restart

### ISSUE THREAD

**Issue by mister-man** [trentech/ProjectInventories#9]
Hallo together,

I have a problem with the current version. After a server restart, all inventories are default. On MySQl-Server the whole data in ok and the connection works.

No errorlogs found

Thanks

Edit:
The old Version used worldnames, the new version use world id's. Is there the problem, that the id change after restart?

The lost version "projectinventories-5.0.0-0.8.1" in github works fine.

**Comment by hugeblank** [comment]
Having this issue as well. After my server restarts all of the inventories for each world gets set to DEFAULT

**Comment by trentech** [comment]
This will be solved in next major update coming soon

**Comment by hugeblank** [comment]
@trentech How soon? :3
